### ISSUE TITLE
Total row numbers

### ISSUE THREAD

**Issue by 772435284** [simaki/fi2010#5]
The total row number of the dataframe is not correct, which is 394,337 in the original paper. The dataframe only has 272941 rows. Something is missing? Maybe there is problem of the split function, which causes some data loss?

**Comment by simaki** [comment]
thanks for a good catch. not really sure but possibly because of the difference between noauction/auction.

**Comment by 772435284** [comment]
https://github.com/zcakhaa/DeepLOB-Deep-Convolutional-Neural-Networks-for-Limit-Order-Books. Check this project, the noaction data has totally 394337 rows.

**Comment by simaki** [comment]
thanks. I am still not sure as I don't know how the data.zip in that repo, which your pr uses too, has been constructed from the original dataset. could you kindly let me learn about it?

**Comment by 772435284** [comment]
The problem is fixed, see latest pull request.

**Comment by simaki** [comment]
ty now i get it
